version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings
    columns:
    - name: listing_id
      description: Primary key for the listing
      tests: 
        - unique
        - not_null
    
    - name: host_id
      description: the host's id. References the host table.
      tests: 
        - not_null
        - relationships: 
            to: ref('dim_hosts_cleansed')
            field: host_id
    
    - name: room_type
      description: The type of the apartment / room
      tests: 
        - accepted_values:
            values: ['Entire home/apt',
                      'Private room',
                      'Shared room',
                      'Hotel room']
    - name: minumum_nights
      description: '{{ doc("dim_listing_cleansed__minumum_nights") }}'
      tests: 
        - positive_value
  - name: dim_hosts_cleansed
    description: Cleansed table which contains Airbnb hosts information
    columns:
      - name: host_id
        description: the host's id.
        tests:
          - not_null
          - unique
      
      - name: host_name
        description: The name of the host
        tests:
          - not_null
      
      - name: is_superhost
        description: Defines whether the hosts is a superhost.
        tests:
          - accepted_values:
              values: ['t', 'f']
      
  - name: dim_listings_w_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb','raw_listings')
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50
              max_value: 500